# Generated by Django 2.2.4 on 2019-10-21 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='alias',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
