# Generated by Django 2.2.4 on 2019-10-21 13:39

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('image', '100x100', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=image_cropping.fields.ImageCropField(upload_to='gallery'),
        ),
    ]
